### ISSUE TITLE
Expanding the package

### ISSUE THREAD

**Issue by leeper** [chainsawriot/rio#1]
I really like this package! It's been implementing something [I've been thinking about for a while](https://gist.github.com/leeper/8d4478b71011ed08db92) but I see you've already created the architecture for exactly what I had in mind. [I've forked the package](https://github.com/leeper/rio) and expanded it considerably with many additional file formats (for foreign, utils, and haven). Seeing as it has been two years since you've worked on this, I wanted to see if you'd accept a pull request for some updates or, if you're not interested in working on the package anymore, if you'd allow me to take over the CRAN maintainership and continue making updates there. Let me know.

Best,
-Thomas

**Comment by chainsawriot** [comment]
Thanks for expanding the RIO package. I think it will be much better for you to take over the CRAN maintainership because I will not have time to maintain it.

**Comment by leeper** [comment]
Okay. Sounds good. I will continue development on my fork and submit to CRAN. You'll probably get an email confirming the package transfer at some point. Thanks!
