### ISSUE TITLE
Feature request: support disk.frame

### ISSUE THREAD

**Issue by xiaodaigh** [chainsawriot/rio#215]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

Can we support disk.frame (http://diskframe.com)? I am the author so keento collaborate.

**Comment by leeper** [comment]
I take it this would be another option in the `setclass` import() option (like what we have for ("data.table" and "tibble")? Seems reasonable. I'm open to a PR here: https://github.com/leeper/rio/blob/master/R/set_class.R if it only adds disk.frame as a Suggests dependency for that functionality.
