### ISSUE TITLE
Add gdal-supported file types (e.g. .tif, .shp) via write_stars and write_sf

### ISSUE THREAD

**Issue by kendonB** [chainsawriot/rio#219]
Please specify whether your issue is about:

 - [x] a suggested code or documentation change, improvement to the code, or feature request

The relevant packages are here:
https://github.com/r-spatial/sf

https://github.com/r-spatial/stars

**Comment by chainsawriot** [comment]
@kendonB Thanks for suggesting this. But it is out of the scope of this package (read and write rectangular data.) 

```r
write_sf(mtcars, 
         tbl = 'test',
         cred_file = 'TODO_cred.R',
         overwrite = TRUE)
```

Would be a quite surprising experience.
