### ISSUE TITLE
Enhancement: try_import()

### ISSUE THREAD

**Issue by bokov** [chainsawriot/rio#238]
I'm not super keen on trying to parse with every imaginable import function. That might produce some kind of unanticipated weird behavior if one of those underlying functions changes to start supporting different kind of file or if we add future functionality that changes the deterministic order of import attempts.

We could add a separate function that does that, though, like `try_import()`.

_Originally posted by @leeper in https://github.com/leeper/rio/issues/180#issuecomment-538634953_

**Comment by rogerjdeangelis** [comment]
Thanks!!!

R is up to 10,000 packages, WOW

**Comment by bokov** [comment]
Working my way toward `try_import()`, first I'm submitting PRs for additional helper functions like `isfiletext()` in #239. Those will permit `try_import()` to be smarter about which import functions are tried and the order in which they are tried.
