### ISSUE TITLE
Clipboard function is also supported in linux differently to what is implied in the documentation of rio::import()

### ISSUE THREAD

**Issue by avila** [chainsawriot/rio#282]
It is a very small issue, but as it is stated in the help file of `?rio::import`, it seems that clipboard is only supported in MacOS or Windows, but it does work fine under linux as well. 

> Clipboard import (on Windows and Mac OS), using read.table with row.names = FALSE

Removing the parenthesis "(on Windows and Mac OS)" should remove doubts whether the feature also works on linux.

**Comment by bokov** [comment]
I can confirm this. I've been using import('clipboard') for years with no problem.
