### ISSUE TITLE
Should we try to get funding for rio devleopment?

### ISSUE THREAD

**Issue by bokov** [chainsawriot/rio#292]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

I've been thinking about what we can do to buy protected time for rio development. Possible directions:

* https://github.com/sponsors/
* https://gitcoin.co/grants/explorer/
* I've been learning about DAOs lately and it seems like fundraising is a major use case. If existing DAOs don't align with the goal of data science tool development, maybe it's time to start one...
* Other ideas?

**Comment by rogerjdeangelis** [comment]
Great package, makes things simple.

I would fund you say $100 a month if you would make available code to
CREATE(not read) V9 SAS SAS7BDATS.

You might want to query your users to see if they would like
theatfunctionality.

Haven is removing that functionality because it never worked

Roger
