### ISSUE TITLE
Unable to load package rio and tidyverse in RStudio for Linux

### ISSUE THREAD

**Issue by jameseconomista** [chainsawriot/rio#298]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality 

If you are reporting (1) a bug or (2) a question about code, please supply:

* DONE (openxlsx)
ERROR: dependency ‘curl’ is not available for package ‘rio’
* removing ‘/home/guidorizieri/R/x86_64-pc-linux-gnu-library/4.0/rio’
Warning in install.packages :
  installation of package ‘rio’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpsuGKwi/downloaded_packages’
> library("rio")
Error in library("rio") : there is no package called ‘rio’
> library(rio)
Error in library(rio) : there is no package called ‘rio’

Put your code here:

```R
## load package
> library(rio)

## code goes here
> library(rio)

## session info for your system
sessionInfo()
```
R4.0.4 Linux (on an Intel Acer 314 Chromebook)

**Comment by bokov** [comment]
You seem to be installing and loading it correctly, all you are missing is curl .

What Linux distro are you using?

If it's Ubuntu (and maybe other Debian-based distros) you need to run `sudo apt-get install curl` and then again try installing rio like you did. 

Please let us know if this fixes your problem.
