### ISSUE TITLE
Feature Request: support for pickle-files

### ISSUE THREAD

**Issue by samuelreuther** [chainsawriot/rio#300]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x ] a suggested code or documentation change, improvement to the code, or feature request

Hello,
I just wanted to suggest the support import and export of pickle-files.
Thank you for considering!
Samuel

**Comment by chainsawriot** [comment]
@samuelreuther Thank you for the suggestion. However, there is currently no R package can directly read pickle files, except maybe implementing it using `reticulate` ourselves. As it is too big a task and pickle files are not always data frame, I think it is out of the scope of this package.
