### ISSUE TITLE
Feature request: triple-s standard support

### ISSUE THREAD

**Issue by aauro** [chainsawriot/rio#302]
Please specify whether your issue is about:

 - [x ] a suggested code or documentation change, improvement to the code, or feature request

Wondering if adding support Triple-s standard is in the roadmap? There is a specific R package called sss.

About triple-s
https://www.triple-s.org/documentation/faq/
Triple-S is a language for describing survey metadata – that is, data about the survey data: question and response texts, the location of individual data items within the record, valid ranges for responses, and so on.

**Comment by chainsawriot** [comment]
https://github.com/chainsawriot/rio/blob/da0a03df2de7490338e5bf77e23d5569a6ecede5/R/extensions.R#L43
